FROM java:8

# ADD . /tmp/ambry
# WORKDIR /tmp/ambry
# RUN ./gradlew allJar


RUN mkdir /ambry
WORKDIR /ambry
COPY releases/ambry.jar .

# config
RUN mkdir config

EXPOSE 1174
# jmx port
EXPOSE 9090

ADD start_frontend.sh .
RUN chmod a+x start_frontend.sh
ENTRYPOINT ["./start_frontend.sh"]

